-- Generated by scripts/build-sync-sql.mjs 1145. Do not edit by hand.
-- Brings "1145" in the live database into line with content/.
-- Overwrites this product's row, documentation and FAQs. Safe to run again.

begin;

-- Hosts that this product's links point to.
update lsicorp.site_settings
set allowed_external_domains = array['play.google.com', 'apps.apple.com', '1145.io']::text[]
where not allowed_external_domains @> array['play.google.com', 'apps.apple.com', '1145.io']::text[];

update lsicorp.products set
  public_name = '1145 Lifestyle',
  internal_name = '1145 Lifestyle',
  mark = '1145',
  tagline = 'Shop, ride and earn in one connected commerce platform.',
  summary = '1145 is LSI''s flagship: a connected marketplace that brings branded online shopping together with the services needed to complete a transaction, from product discovery and merchant storefronts to delivery, rides and digital financial tools.',
  category = 'Commerce',
  sort_order = 1,
  status = 'available',
  status_note = '1145 Lifestyle is live as a web app at 1145.io. It runs in your browser, so there is nothing to download.',
  audiences = '[{"name":"Consumers","description":"People who want to discover, buy and receive products, and use related services, in one place."},{"name":"Merchants and brand owners","description":"Businesses that want their own storefront, with tools to list products, manage orders and reach customers."},{"name":"Delivery partners and drivers","description":"People who fulfil deliveries and rides through the platform."}]'::jsonb,
  capabilities = '[{"name":"Marketplace and brand storefronts","group":"Customer shopping","availability":"available","description":"Browse categories, deals and new arrivals from many sellers, each with their own storefront."},{"name":"Merchant tools","group":"Merchants","availability":"available","description":"Register as a merchant, set up a store, list products, manage stock and orders, and see how the store is performing."},{"name":"Secure checkout and payments","group":"Payments","availability":"available","description":"Pay for an order through an integrated, encrypted checkout."},{"name":"Order tracking and delivery","group":"Logistics","availability":"available","description":"Follow an order from purchase to delivery, with the logistics layer connecting merchants to drivers."},{"name":"Rides","group":"Logistics","availability":"available","description":"Request and manage rides through the same account."},{"name":"Wallet and rewards","group":"Payments","availability":"available","description":"A wallet and rewards connected to activity on the platform. The terms on 1145.io apply to any financial feature."},{"name":"Mobile apps","group":"Platforms","availability":"planned","description":"Android and iOS apps are planned. Until they are released, use the web app in your phone’s browser."},{"name":"Product recommendations","group":"Customer shopping","availability":"planned","description":"AI-assisted recommendations are on the roadmap."},{"name":"More languages and currencies","group":"Platforms","availability":"planned","description":"Multi-language and multi-currency support is on the roadmap."}]'::jsonb,
  requirements = '[{"label":"Device","detail":"Any phone, tablet or computer with a current web browser. The web app adapts to the screen."},{"label":"Account","detail":"A 1145 account, created on 1145.io. This website never asks for your 1145 sign-in or payment details."},{"label":"Connectivity","detail":"An internet connection."}]'::jsonb,
  services = array['digital-platforms', 'logistics-technology', 'financial-technology']::text[],
  platforms = array['web']::text[],
  platform_note = '1145 is a web app for now. There are no downloadable apps; mobile apps are planned.',
  getting_started = 'Open 1145 in your browser and create an account. You can start shopping straight away, or register as a merchant to open a store.',
  limitations = array['There are no mobile apps to download yet. Use the web app in your phone’s browser.', 'Which services are offered can differ by location.', 'Payments, wallet and rewards are governed by the terms published on 1145.io, not by this website.']::text[],
  notice_title = null,
  notice_body = null,
  support_url = null,
  privacy_url = null,
  icon_path = null
where slug = '1145';

insert into lsicorp.doc_pages (product_slug, slug, title, summary, audience, sort_order, body, last_reviewed, status)
values ('1145', 'getting-started', 'Getting started with 1145 Lifestyle', 'Open the web app, create an account and place a first order or open a store.', 'Everyone', 1, '1145 Lifestyle is live as a web app. It runs in your browser, so there is nothing to install.

## What you need

- A phone, tablet or computer with a current web browser and an internet connection.
- A 1145 account. You create it on 1145.io, never on this website.

## Open 1145

1. Go to the [1145 Lifestyle page](/work/1145) and choose **Open 1145 Lifestyle**. The link leaves this website and opens 1145.io.
2. Create an account, or sign in if you already have one.

## If you are shopping

Browse the categories, deals and storefronts, add what you want to your basket and check out. You can follow the order to delivery from your account.

## If you are selling

Register as a merchant and set up your store. Each merchant has their own storefront, with tools for products, stock and orders.

## On a phone

There are no mobile apps to download yet. Open 1145.io in your phone''s browser; the web app adapts to the screen.
', '2026-10-06', 'published')
on conflict (product_slug, slug) do update set
  title = excluded.title,
  summary = excluded.summary,
  audience = excluded.audience,
  sort_order = excluded.sort_order,
  body = excluded.body,
  last_reviewed = excluded.last_reviewed,
  status = excluded.status;

insert into lsicorp.doc_pages (product_slug, slug, title, summary, audience, sort_order, body, last_reviewed, status)
values ('1145', 'services', 'What 1145 brings together', 'The marketplace, merchant tools, delivery, rides and financial features in one platform.', 'Everyone', 2, '1145 is built as a connected ecosystem: you use the services relevant to you, and they work together.

## Available now

- **Marketplace and brand storefronts.** Discover and buy products from many sellers.
- **Merchant tools.** Product listings, stock, orders and store performance.
- **Secure checkout and payments.** An integrated, encrypted checkout.
- **Order tracking and delivery.** A logistics layer connects a sale to the delivery that completes it.
- **Rides.** Request and manage rides through the same account.
- **Wallet and rewards.** Connected to your activity on the platform.

The terms published on 1145.io apply to every payment, wallet and rewards feature.

## Planned

- Mobile apps for Android and iOS.
- Product recommendations.
- More languages and currencies.

Planned features are not available yet and may change.
', '2026-10-06', 'published')
on conflict (product_slug, slug) do update set
  title = excluded.title,
  summary = excluded.summary,
  audience = excluded.audience,
  sort_order = excluded.sort_order,
  body = excluded.body,
  last_reviewed = excluded.last_reviewed,
  status = excluded.status;

insert into lsicorp.doc_pages (product_slug, slug, title, summary, audience, sort_order, body, last_reviewed, status)
values ('1145', 'troubleshooting', 'Troubleshooting 1145 Lifestyle', 'Where to get help with an account, order, ride or payment.', 'Everyone', 3, '## I cannot find an app to download

There is none yet. 1145 is a web app: open it from the [1145 Lifestyle page](/work/1145) in your browser, including on a phone.

## I have a problem with an order, a ride or a payment

Use the help and contact options on 1145.io. The 1145 support team can see your account and order; this website cannot.

## Someone sent me a link to a 1145 app or sign-in page

Only use the link published on this website, which opens 1145.io. Treat any other address or any app file as unofficial, and never enter your sign-in details there.

## The page will not load

Check your connection and try a current browser. If the problem continues, see [Support](/support).
', '2026-10-06', 'published')
on conflict (product_slug, slug) do update set
  title = excluded.title,
  summary = excluded.summary,
  audience = excluded.audience,
  sort_order = excluded.sort_order,
  body = excluded.body,
  last_reviewed = excluded.last_reviewed,
  status = excluded.status;

delete from lsicorp.doc_pages
where product_slug = '1145' and slug not in ('getting-started', 'services', 'troubleshooting');

delete from lsicorp.faqs where product_slug = '1145';

insert into lsicorp.faqs (product_slug, question, answer, category, escalation, visible, sort_order)
values ('1145', 'Can I use 1145 Lifestyle today?', 'Yes. 1145 is live as a web app at 1145.io. Use the Open 1145 Lifestyle button on its page.', 'Availability', null, true, 1);

insert into lsicorp.faqs (product_slug, question, answer, category, escalation, visible, sort_order)
values ('1145', 'Is there an app to download?', 'Not yet. 1145 runs in your browser on a phone, tablet or computer. Android and iOS apps are planned, and will be listed on the Downloads page when they are released.', 'Availability', null, true, 2);

insert into lsicorp.faqs (product_slug, question, answer, category, escalation, visible, sort_order)
values ('1145', 'Where do I sign in?', 'On 1145.io. This website is LSI’s company site and never asks for your 1145 sign-in or payment details.', 'Accounts', null, true, 3);

insert into lsicorp.faqs (product_slug, question, answer, category, escalation, visible, sort_order)
values ('1145', 'How do I sell on 1145?', 'Register as a merchant on 1145.io. Each merchant gets their own storefront, with tools for products, stock and orders.', 'Merchants', null, true, 4);

insert into lsicorp.faqs (product_slug, question, answer, category, escalation, visible, sort_order)
values ('1145', 'Who do I contact about an order, a ride or a payment?', 'Use the help and contact options on 1145.io, where your account and order details are available to the support team.', 'Support', null, true, 5);

-- 1145-web-live.json
insert into lsicorp.releases (product_slug, platform, version, channel, status, release_date, destination_type, destination_url, artifact_filename, artifact_file_type, artifact_size_bytes, artifact_sha256, compat_minimum, compat_device_class, compat_dependencies, steps, notes, known_issues, licence, support_route)
values ('1145', 'web', 'live', 'stable', 'available', '2026-10-06', 'web-app', 'https://1145.io', null, null, null, null, 'A current web browser', 'Phones, tablets and computers', '{}'::text[], array['Choose Open 1145 Lifestyle. The link leaves this website and opens 1145.io.', 'Create an account, or sign in if you already have one. You do this on 1145.io, never on this website.', 'Start shopping, or register as a merchant to open a store.']::text[], array['1145 Lifestyle is live for online use as a web app.', 'The web app is updated continuously, so it does not have a version number here. The date shown is when it was listed on this website.']::text[], array['There are no mobile apps to download yet. Use the web app in your phone’s browser.']::text[], 'Copyright LSI. All rights reserved. Use of 1145 is subject to the terms published on 1145.io.', 'Use the help and contact options on 1145.io for anything about your account, an order, a ride or a payment.')
on conflict (product_slug, platform, version) do update set
  channel = excluded.channel,
  status = excluded.status,
  release_date = excluded.release_date,
  destination_type = excluded.destination_type,
  destination_url = excluded.destination_url,
  artifact_filename = excluded.artifact_filename,
  artifact_file_type = excluded.artifact_file_type,
  artifact_size_bytes = excluded.artifact_size_bytes,
  artifact_sha256 = excluded.artifact_sha256,
  compat_minimum = excluded.compat_minimum,
  compat_device_class = excluded.compat_device_class,
  compat_dependencies = excluded.compat_dependencies,
  steps = excluded.steps,
  notes = excluded.notes,
  known_issues = excluded.known_issues,
  licence = excluded.licence,
  support_route = excluded.support_route;

commit;
